#!/bin/bash
local='http://localhost:8080'
#host='http://cosmoresource.ru/'
host='http://reality.satellite.dvo.ru:8888/welcome'
i=1
j=2
collections='/rest/repo/collections'
collect_prod='/rest/repo/collections?products='
components='/rest/repo/components/'
comp_prod='/rest/repo/components?products='
products='/rest/repo/products/'
protocols_out='/rest/repo/protocols-out'
protocols_in='/rest/repo/protocols-in'
resources='/rest/repo/resources/'
slots_in="/rest/repo/slots-in"
confirm="/confirm"
slots_out="/rest/repo/slots-out/"
slots_out_zip='/rest/repo/slots-out/http-zipped/'
